# Generated by Django 3.0.8 on 2021-09-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='license',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
