# Generated by Django 3.0.8 on 2021-09-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sortno',
            new_name='regno',
        ),
        migrations.AddField(
            model_name='product',
            name='make',
            field=models.CharField(choices=[('Isuzu', 'Isuzu'), ('Volvo', 'Volvo'), ('Hyundai', 'Hyundai'), ('Scania', 'Scania'), ('MAN', 'MAN'), ('TataGroup', 'TataGroup')], max_length=10, null=True),
        ),
    ]
