# Generated by Django 3.0.8 on 2021-09-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210926_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='regno',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflowID', models.CharField(max_length=50)),
                ('destination', models.CharField(choices=[('NAIROBI', 'NAIROBI'), ('MOMBASA', 'MOMBASA'), ('KISUMU', 'KISUMU'), ('NAIVASHA', 'NAIVASHA'), ('BUSIA', 'BUSIA')], max_length=10, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Driver')),
                ('plate_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
    ]
